### ISSUE TITLE
standard testing of benchmark and model additions

### ISSUE THREAD

**Issue by mschrimpf** [brain-score/core#21]
To ensure that new benchmarks and models actually run through, we should add our own tests that provide a dummy model or dummy benchmark and simulate an entire benchmark or model run respectively. Otherwise we might merge new plugins that don't actually run properly.

We might need to do this separately for each domain, i.e. dummy model+benchmark for language, and the same for vision (and all future domains).

@kvfairchild

**Comment by kvfairchild** [comment]
Core infrastructure put in place by https://github.com/brain-score/core/pull/72

Solved for [vision models](https://github.com/brain-score/vision/pull/433); issues created in corresponding domain repositories for [vision benchmarks](https://github.com/brain-score/vision/issues/605), [language models](https://github.com/brain-score/language/issues/234), and [language benchmarks](https://github.com/brain-score/language/issues/177).
